---
title: "My Spotify"
author: "LA"
date: "12/21/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Libraries ---------------------------------------------------------------
library(visNetwork)
library(geomnet) #devtools::install_github("sctyner/geomnet") #devtools::install_version('geomnet', '0.3.1', repos="https://cran.rstudio.com/")
library(igraph)
library(spotifyr)
library(tidyverse)
library(knitr)
library(lubridate)
library(plotly)
library(ggplot2)
library(wordcloud2) 
library(ggExtra)

# Resources
#https://www.kaylinpavlik.com/classifying-songs-genres/
#https://www.reddit.com/r/spotify/comments/50b2p9/every_noise_at_once_a_genre_map_with/
#https://www.reddit.com/r/dataisbeautiful/comments/h7uoia/oc_network_of_artist_genres_in_spotify/
#https://www.rcharlie.com/spotifyr/ 
#http://developer.spotify.com/community/showcase/music-popcorn/

```

### Data Preparation

```{r}
# Data Preparation --------------------------------------------------------
# Follow the instructions here: https://www.rcharlie.com/spotifyr/ 
if(!exists('track_features')){

  id <- 'a41f9a0aea274995a97901daeef8fea5'
  secret <- '1b9b37c00c814902a7b22980ab2da1c7'
  Sys.setenv(SPOTIFY_CLIENT_ID = id)
  Sys.setenv(SPOTIFY_CLIENT_SECRET = secret)
  access_token <- get_spotify_access_token()
  
  # More permissions needed. This requires having http://localhost:1410/ added to the list of redirect URL's through https://developer.spotify.com/dashboard/applications/ 
  my_id <- '12162125686'
  
  # Get my saved songs 
  tracks <- data.frame()
  artists_genres <- data.frame()
  track_features <- data.frame()
  
  i_max = 221
  limit = 25
  
  for(i in 1:i_max){
    print(paste0("Running ", i , " out of ", i_max))
  
    offset = limit * i - limit 
    
    tracks_tmp <- get_my_saved_tracks(limit = limit, offset = offset) %>%
      unnest(track.artists) %>%
      unnest(track.album.release_date) %>%
      unique() %>%
      filter(!is.null(name))
    
    artists_genres_tmp <- get_artists(unique(tracks_tmp$id)) 
    # artists_genres_tmp <- get_artists(unique(tracks_tmp$id)) 
    
    track_features_tmp <- get_track_audio_features(tracks_tmp$track.id)
    
    tracks <- rbind(tracks, tracks_tmp)
    artists_genres <- rbind(artists_genres, artists_genres_tmp)
    track_features <- rbind(track_features, track_features_tmp)
  }
  
  
  names(artists_genres) <- paste("genre", names(artists_genres), sep="_")
  names(track_features) <- paste("features", names(track_features), sep="_")
  
  artists_tracks_merge <- merge(tracks, artists_genres, by.x = "id", by.y = "genre_id" ) %>%
    mutate(date_raw = track.album.release_date) %>%
    #select(date_raw) %>%
    mutate(date_date = as.Date(date_raw, format="%Y-%m-%d")) %>%
    mutate(date_year = ifelse(is.na(date_date), date_raw, year(date_date))) %>%
    mutate(date_year = as.numeric(date_year)) %>%
    mutate(qty = 1) %>%
    group_by(name, date_year) %>%
    mutate(artist_qty = sum(qty)) %>%
    ungroup() %>%
    arrange(date_year)
  
  track_features_artists_tracks_merge <- merge(artists_tracks_merge, track_features, by.x = "track.id", by.y = "features_id")
  
}

```

### Visualization over time

```{r}
#### Visualization over time ####
g <- ggplot(artists_tracks_merge, aes(x=date_year, y=qty, fill = paste0(name))) + 
  geom_bar(position="stack", stat = "identity", width=0.9) +
  scale_fill_manual("legend", values = rep_len( c("skyblue"), nrow(artists_tracks_merge))) +
  theme_bw() + 
  theme(legend.position="none")
p <- ggplotly(g)
p

```

### Visualization of circle bar chart

```{r}
#### Visualization of circle bar chart ####
#Data wrangling for genres circular bar chart
data <- artists_tracks_merge %>%
  select(genre_genres, genre_name, qty) %>%
  unnest(genre_genres) %>%
  group_by(genre_genres) %>%
  summarize(value = sum(qty)) %>%
  ungroup() %>%
  arrange(value) %>%
  mutate(id = row_number()) %>%
  mutate(individual = genre_genres)

# Get the name and the y position of each label
label_data <- data

# calculate the ANGLE of the labels
number_of_bar <- nrow(label_data)
angle <-  90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)

# calculate the alignment of labels: right or left
# If I am on the left part of the plot, my labels have currently an angle < -90
label_data$hjust<-ifelse( angle < -90, 1, 0)

# flip angle BY to make them readable
label_data$angle<-ifelse(angle < -90, angle+180, angle)

# Start the plot
p <- ggplot(data, aes(x=as.factor(id), y=value)) +       # Note that id is a factor. If x is numeric, there is some space between the first bar
  
  # This add the bars with a blue color
  geom_bar(stat="identity", fill=alpha("skyblue", 0.7)) +
  
  # Limits of the plot = very important. The negative value controls the size of the inner circle, the positive one is useful to add size over each bar
  ylim(-100,120) +
  
  # Custom the theme: no axis title and no cartesian grid
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm")      # Adjust the margin to make in sort labels are not truncated!
  ) +
  
  # This makes the coordinate polar instead of cartesian.
  coord_polar(start = 0) +
  
  # Add the labels, using the label_data dataframe that we have created before
  geom_text(data=label_data, aes(x=id, y=value+10, label=individual, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2.5, angle= label_data$angle, inherit.aes = FALSE ) 

p
```

### Visualization of wordcloud

```{r}
#### Visualization of wordcloud ####
# wordcloud2(data %>% rename("word" = "genre_genres", "freq" = "value") %>% select(word, freq), size=0.5, color='random-light', backgroundColor="black") #color=rep_len( c("green","blue"), nrow(demoFreq) )
wordcloud2(data %>% rename("word" = "genre_genres", "freq" = "value") %>% select(word, freq), size=0.5, color='skyblue', backgroundColor="white") #color=rep_len( c("green","blue"), nrow(demoFreq) )

```

### Visualization by features {.tabset}

#### Danceability vs Acousticness

```{r}
#### Visualization by features ####
data2 <- track_features_artists_tracks_merge %>%
  unnest(genre_genres)

p <- ggplot(data2, aes(x=features_danceability, y=features_acousticness, fill=name, color=genre_genres)) + #, size=cyl
  geom_point() +
  scale_fill_manual("legend", values = rep_len( c("skyblue"), nrow(artists_tracks_merge))) +
  theme_bw() + 
  theme(legend.position="none")
ggplotly(p)
```



### Resources
 - https://www.kaylinpavlik.com/classifying-songs-genres/
 - https://www.reddit.com/r/spotify/comments/50b2p9/every_noise_at_once_a_genre_map_with/
 - https://www.reddit.com/r/dataisbeautiful/comments/h7uoia/oc_network_of_artist_genres_in_spotify/
 - https://www.rcharlie.com/spotifyr/ 
 - http://developer.spotify.com/community/showcase/music-popcorn/
